# Generated by Django 5.2.13 on 2026-04-21 10:47

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HiveUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=16, unique=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("admin", "Admin")],
                        default="user",
                        max_length=16,
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("profile_image", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hive user",
                "verbose_name_plural": "Hive users",
                "db_table": "users",
            },
        ),
    ]
