# Generated by Django 5.2.13 on 2026-04-22 00:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("google", "Google"), ("github", "GitHub")],
                        max_length=30,
                    ),
                ),
                ("provider_user_id", models.CharField(max_length=255)),
                (
                    "provider_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_accounts",
                        to="accounts.hiveuser",
                    ),
                ),
            ],
            options={
                "db_table": "oauth_accounts",
            },
        ),
        migrations.AddConstraint(
            model_name="oauthaccount",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_user_id"),
                name="uq_oauth_accounts_provider_user",
            ),
        ),
    ]
