# Generated by Django 5.2.13 on 2026-05-16 14:35

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_oauthaccount"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "DO $$ "
                "BEGIN "
                "IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_type') THEN "
                "CREATE TYPE notification_type AS ENUM ("
                "'post_liked', "
                "'comment_liked', "
                "'post_commented', "
                "'comment_replied'"
                "); "
                "END IF; "
                "IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_target_type') THEN "
                "CREATE TYPE notification_target_type AS ENUM ('post', 'comment'); "
                "END IF; "
                "END $$;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    apps.core.models.PostgresEnumField(
                        choices=[
                            ("post_liked", "Post liked"),
                            ("comment_liked", "Comment liked"),
                            ("post_commented", "Post commented"),
                            ("comment_replied", "Comment replied"),
                        ],
                        enum_type="notification_type",
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "target_type",
                    apps.core.models.PostgresEnumField(
                        blank=True,
                        choices=[("post", "Post"), ("comment", "Comment")],
                        enum_type="notification_target_type",
                        max_length=40,
                        null=True,
                    ),
                ),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="accounts.hiveuser",
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "managed": False,
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "-created_at", "-id"],
                name="notifications_user_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"],
                name="notifications_user_unread_idx",
            ),
        ),
    ]
