# Generated by Django 5.2.13 on 2026-05-16 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_notification"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "CREATE TABLE IF NOT EXISTS notifications ("
                "id uuid PRIMARY KEY DEFAULT gen_random_uuid(), "
                "user_id uuid NOT NULL, "
                "notification_type notification_type NOT NULL, "
                "title varchar(255) NOT NULL, "
                "body text, "
                "target_type notification_target_type, "
                "target_id uuid, "
                "is_read boolean NOT NULL DEFAULT false, "
                "created_at timestamptz NOT NULL DEFAULT now(), "
                "read_at timestamptz, "
                "CONSTRAINT fk_notifications_user "
                "FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE"
                "); "
                "CREATE INDEX IF NOT EXISTS notifications_user_created_idx "
                "ON notifications (user_id, created_at DESC, id DESC); "
                "CREATE INDEX IF NOT EXISTS notifications_user_unread_idx "
                "ON notifications (user_id, is_read, created_at DESC);"
            ),
            reverse_sql=(
                "DROP INDEX IF EXISTS notifications_user_unread_idx; "
                "DROP INDEX IF EXISTS notifications_user_created_idx; "
                "DROP TABLE IF EXISTS notifications;"
            ),
        ),
    ]
