# Generated by Django 5.2.13 on 2026-05-16 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_create_notifications_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "db_table": "notifications",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
