# Generated by Django 5.2.13 on 2026-05-02 05:15

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("target_url", models.TextField()),
                ("enabled", models.BooleanField(default=True)),
                ("poll_interval_minutes", models.IntegerField(default=30)),
                (
                    "next_poll_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("initial_backfill_done", models.BooleanField(default=False)),
                ("backfill_completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_message", models.TextField(blank=True, null=True)),
                ("consecutive_failures", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "sources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.CharField(max_length=50, unique=True)),
                (
                    "tag_type",
                    models.CharField(
                        choices=[("user", "User"), ("system", "System")],
                        default="user",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SourceDocument",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("canonical_url", models.TextField()),
                ("title", models.TextField()),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("body_text", models.TextField(blank=True, null=True)),
                (
                    "fetch_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("FETCHED", "Fetched"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("fetch_retry_count", models.IntegerField(default=0)),
                ("fetch_error_message", models.TextField(blank=True, null=True)),
                (
                    "wiki_status",
                    models.CharField(
                        choices=[
                            ("NOT_REQUESTED", "Not requested"),
                            ("REQUESTED", "Requested"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="NOT_REQUESTED",
                        max_length=20,
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "source",
                    models.ForeignKey(
                        db_column="source_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.source",
                    ),
                ),
            ],
            options={
                "db_table": "source_documents",
            },
        ),
        migrations.CreateModel(
            name="SourceChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chunk_index", models.IntegerField()),
                ("chunk_type", models.CharField(blank=True, max_length=30, null=True)),
                ("section_title", models.TextField(blank=True, null=True)),
                ("content_text", models.TextField()),
                ("token_count", models.IntegerField(blank=True, null=True)),
                ("char_start", models.IntegerField(blank=True, null=True)),
                ("char_end", models.IntegerField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        db_column="source_document_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="core.sourcedocument",
                    ),
                ),
            ],
            options={
                "db_table": "source_chunks",
            },
        ),
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("STARTED", "Started"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("queued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_document",
                    models.ForeignKey(
                        db_column="source_document_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_jobs",
                        to="core.sourcedocument",
                    ),
                ),
            ],
            options={
                "db_table": "ingestion_jobs",
            },
        ),
        migrations.AddConstraint(
            model_name="sourcedocument",
            constraint=models.UniqueConstraint(
                fields=("source", "canonical_url"),
                name="source_documents_source_id_canonical_url_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcechunk",
            constraint=models.UniqueConstraint(
                fields=("source_document", "chunk_index"),
                name="uq_source_chunks_document_chunk_index",
            ),
        ),
    ]
