# Generated by Django 5.2.13 on 2026-05-07 07:50

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_oauthaccount"),
        ("core", "0002_wiki_models"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "DO $$ "
                "BEGIN "
                "IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tag_type') THEN "
                "CREATE TYPE tag_type AS ENUM ('system', 'user'); "
                "END IF; "
                "IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'post_status') THEN "
                "CREATE TYPE post_status AS ENUM ('published', 'draft', 'deleted'); "
                "END IF; "
                "IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'comment_status') THEN "
                "CREATE TYPE comment_status AS ENUM ('published', 'deleted'); "
                "END IF; "
                "END $$;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE tags "
                        "ALTER COLUMN tag_type TYPE tag_type "
                        "USING tag_type::tag_type;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE tags "
                        "ALTER COLUMN tag_type TYPE varchar(20) "
                        "USING tag_type::text;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="tag",
                    name="tag_type",
                    field=apps.core.models.PostgresEnumField(
                        choices=[("user", "User"), ("system", "System")],
                        default="user",
                        enum_type="tag_type",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "status",
                    apps.core.models.PostgresEnumField(
                        choices=[("published", "Published"), ("deleted", "Deleted")],
                        default="published",
                        enum_type="comment_status",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author_user",
                    models.ForeignKey(
                        blank=True,
                        db_column="author_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to="accounts.hiveuser",
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_comment_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="core.comment",
                    ),
                ),
            ],
            options={
                "db_table": "comments",
            },
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "comment",
                        "user",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        db_column="comment_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_likes",
                        to="core.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_likes",
                        to="accounts.hiveuser",
                    ),
                ),
            ],
            options={
                "db_table": "comment_likes",
            },
        ),
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_comments",
                through="core.CommentLike",
                to="accounts.hiveuser",
            ),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content_markdown", models.TextField()),
                (
                    "status",
                    apps.core.models.PostgresEnumField(
                        choices=[
                            ("published", "Published"),
                            ("draft", "Draft"),
                            ("deleted", "Deleted"),
                        ],
                        default="published",
                        enum_type="post_status",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "author_user",
                    models.ForeignKey(
                        blank=True,
                        db_column="author_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="accounts.hiveuser",
                    ),
                ),
            ],
            options={
                "db_table": "posts",
            },
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                db_column="post_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="core.post",
            ),
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "post",
                        "user",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_likes",
                        to="core.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_likes",
                        to="accounts.hiveuser",
                    ),
                ),
            ],
            options={
                "db_table": "post_likes",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_posts",
                through="core.PostLike",
                to="accounts.hiveuser",
            ),
        ),
        migrations.CreateModel(
            name="PostTag",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "post",
                        "tag",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_tags",
                        to="core.post",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        db_column="tag_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_tags",
                        to="core.tag",
                    ),
                ),
            ],
            options={
                "db_table": "post_tags",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                related_name="posts", through="core.PostTag", to="core.tag"
            ),
        ),
    ]
