# Generated by Django 5.2.13 on 2026-05-07 08:28

import re

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

WIKI_LINK_RE = re.compile(r"/wiki/(?P<slug>[-\w]+)/")


def backfill_post_wiki_documents(apps, schema_editor):
    Post = apps.get_model("core", "Post")
    PostWikiDocument = apps.get_model("core", "PostWikiDocument")
    WikiDocument = apps.get_model("core", "WikiDocument")

    documents_by_slug = {
        document.slug: document.id for document in WikiDocument.objects.all()
    }
    through_rows = []
    seen_pairs = set()
    for post in Post.objects.all().iterator():
        for match in WIKI_LINK_RE.finditer(post.content_markdown or ""):
            slug = match.group("slug")
            wiki_document_id = documents_by_slug.get(slug)
            if wiki_document_id is None:
                continue
            pair = (post.id, wiki_document_id)
            if pair in seen_pairs:
                continue
            seen_pairs.add(pair)
            through_rows.append(
                PostWikiDocument(
                    post_id=post.id,
                    wiki_document_id=wiki_document_id,
                )
            )

    if through_rows:
        PostWikiDocument.objects.bulk_create(through_rows, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_tag_tag_type_comment_commentlike_comment_likes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostWikiDocument",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "post",
                        "wiki_document",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_wiki_documents",
                        to="core.post",
                    ),
                ),
                (
                    "wiki_document",
                    models.ForeignKey(
                        db_column="wiki_document_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_wiki_documents",
                        to="core.wikidocument",
                    ),
                ),
            ],
            options={
                "db_table": "post_wiki_documents",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="wiki_documents",
            field=models.ManyToManyField(
                related_name="community_posts",
                through="core.PostWikiDocument",
                to="core.wikidocument",
            ),
        ),
        migrations.RunPython(backfill_post_wiki_documents, noop_reverse),
    ]
