# Generated by Django 5.2.13 on 2026-05-07 08:28

import re

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

WIKI_LINK_RE = re.compile(r"/wiki/(?P<slug>[-\w]+)/")
POST_ITERATOR_CHUNK_SIZE = 1000
THROUGH_BULK_CREATE_BATCH_SIZE = 500


def backfill_post_wiki_documents(apps, schema_editor):
    Post = apps.get_model("core", "Post")
    PostWikiDocument = apps.get_model("core", "PostWikiDocument")
    WikiDocument = apps.get_model("core", "WikiDocument")

    documents_by_slug = {
        document.slug: document.id
        for document in WikiDocument.objects.only("id", "slug")
    }
    through_rows = []
    posts = Post.objects.filter(content_markdown__contains="/wiki/").only(
        "id", "content_markdown"
    )
    for post in posts.iterator(chunk_size=POST_ITERATOR_CHUNK_SIZE):
        seen_wiki_document_ids = set()
        for match in WIKI_LINK_RE.finditer(post.content_markdown or ""):
            slug = match.group("slug")
            wiki_document_id = documents_by_slug.get(slug)
            if wiki_document_id is None or wiki_document_id in seen_wiki_document_ids:
                continue
            seen_wiki_document_ids.add(wiki_document_id)
            through_rows.append(
                PostWikiDocument(
                    post_id=post.id,
                    wiki_document_id=wiki_document_id,
                )
            )
            if len(through_rows) >= THROUGH_BULK_CREATE_BATCH_SIZE:
                PostWikiDocument.objects.bulk_create(
                    through_rows,
                    batch_size=THROUGH_BULK_CREATE_BATCH_SIZE,
                    ignore_conflicts=True,
                )
                through_rows = []

    if through_rows:
        PostWikiDocument.objects.bulk_create(
            through_rows,
            batch_size=THROUGH_BULK_CREATE_BATCH_SIZE,
            ignore_conflicts=True,
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_tag_tag_type_comment_commentlike_comment_likes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostWikiDocument",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "post",
                        "wiki_document",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_wiki_documents",
                        to="core.post",
                    ),
                ),
                (
                    "wiki_document",
                    models.ForeignKey(
                        db_column="wiki_document_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_wiki_documents",
                        to="core.wikidocument",
                    ),
                ),
            ],
            options={
                "db_table": "post_wiki_documents",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="wiki_documents",
            field=models.ManyToManyField(
                related_name="community_posts",
                through="core.PostWikiDocument",
                to="core.wikidocument",
            ),
        ),
        migrations.RunPython(backfill_post_wiki_documents, noop_reverse),
    ]
