import re

from django.db import migrations, models
from django.utils import timezone

import apps.core.models

HEADING_RE = re.compile(r"^(#{1,6})\s+(.*?)(?:\s+#+\s*)?$")
MARKDOWN_LINK_RE = re.compile(r"!?(\[([^\]]+)\]\([^)]+\))")
INLINE_CODE_RE = re.compile(r"`([^`]*)`")
MARKDOWN_DECORATION_RE = re.compile(r"[*_~>#-]+")
MULTISPACE_RE = re.compile(r"\s+")
POST_BULK_UPDATE_BATCH_SIZE = 500
COMMENT_BULK_UPDATE_BATCH_SIZE = 500


def _plain_text(value: str) -> str:
    text = MARKDOWN_LINK_RE.sub(r"\2", value)
    text = INLINE_CODE_RE.sub(r"\1", text)
    text = MARKDOWN_DECORATION_RE.sub(" ", text)
    return MULTISPACE_RE.sub(" ", text).strip()


def _normalize_line(value: str) -> str:
    return MULTISPACE_RE.sub(" ", value.strip())


def _extract_post_title_and_body(content_markdown: str) -> tuple[str, str]:
    if not content_markdown:
        return "", ""

    lines = content_markdown.splitlines()
    first_content_index = next(
        (index for index, line in enumerate(lines) if line.strip()),
        None,
    )
    if first_content_index is None:
        return "", ""

    first_line = lines[first_content_index].strip()
    heading_match = HEADING_RE.match(first_line)
    if heading_match and len(heading_match.group(1)) == 1:
        title = _plain_text(heading_match.group(2))
        body_lines = lines[first_content_index + 1 :]
        while body_lines and not body_lines[0].strip():
            body_lines.pop(0)
        return title, "\n".join(body_lines).strip()

    title = _normalize_line(_plain_text(first_line))
    return title, content_markdown.strip()


def _extract_post_render_parts(
    content_markdown: str, *, excerpt_max_length: int = 180
) -> tuple[str, str, str]:
    title, body_markdown = _extract_post_title_and_body(content_markdown)
    normalized_content = content_markdown.strip() if content_markdown else ""
    display_body = body_markdown or normalized_content
    plain_text = _normalize_line(_plain_text(display_body))
    if len(plain_text) <= excerpt_max_length:
        excerpt = plain_text
    else:
        excerpt = plain_text[: excerpt_max_length - 1].rstrip() + "…"
    return title, display_body, excerpt


def backfill_soft_delete_and_post_cache_fields(apps, schema_editor):
    Post = apps.get_model("core", "Post")
    Comment = apps.get_model("core", "Comment")
    now = timezone.now()

    posts_to_update = []
    for post in Post.objects.all().iterator(chunk_size=POST_BULK_UPDATE_BATCH_SIZE):
        title, body_markdown, summary = _extract_post_render_parts(
            post.content_markdown or ""
        )
        post.title_cache = title
        post.body_markdown_cache = body_markdown
        post.summary_cache = summary
        if post.status == "deleted":
            if post.deleted_at is None:
                post.deleted_at = post.updated_at or post.created_at or now
            post.status = "draft"
        posts_to_update.append(post)
        if len(posts_to_update) >= POST_BULK_UPDATE_BATCH_SIZE:
            Post.objects.bulk_update(
                posts_to_update,
                [
                    "title_cache",
                    "body_markdown_cache",
                    "summary_cache",
                    "deleted_at",
                    "status",
                ],
                batch_size=POST_BULK_UPDATE_BATCH_SIZE,
            )
            posts_to_update = []

    if posts_to_update:
        Post.objects.bulk_update(
            posts_to_update,
            [
                "title_cache",
                "body_markdown_cache",
                "summary_cache",
                "deleted_at",
                "status",
            ],
            batch_size=POST_BULK_UPDATE_BATCH_SIZE,
        )

    comments_to_update = []
    for comment in Comment.objects.all().iterator(
        chunk_size=COMMENT_BULK_UPDATE_BATCH_SIZE
    ):
        if comment.content is None:
            comment.content = ""
        if comment.status == "deleted" and comment.deleted_at is None:
            comment.deleted_at = comment.updated_at or comment.created_at or now
        comments_to_update.append(comment)
        if len(comments_to_update) >= COMMENT_BULK_UPDATE_BATCH_SIZE:
            Comment.objects.bulk_update(
                comments_to_update,
                ["content", "deleted_at"],
                batch_size=COMMENT_BULK_UPDATE_BATCH_SIZE,
            )
            comments_to_update = []

    if comments_to_update:
        Comment.objects.bulk_update(
            comments_to_update,
            ["content", "deleted_at"],
            batch_size=COMMENT_BULK_UPDATE_BATCH_SIZE,
        )


THROUGH_TABLES_FORWARD_SQL = """
CREATE TABLE comment_likes_new (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    comment_id uuid NOT NULL REFERENCES comments (id) DEFERRABLE INITIALLY DEFERRED,
    user_id uuid NOT NULL REFERENCES users (id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT comment_likes_comment_id_user_id_key UNIQUE (comment_id, user_id)
);
INSERT INTO comment_likes_new (comment_id, user_id, created_at)
SELECT comment_id, user_id, created_at
FROM comment_likes;
DROP TABLE comment_likes;
ALTER TABLE comment_likes_new RENAME TO comment_likes;

CREATE TABLE post_likes_new (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    post_id uuid NOT NULL REFERENCES posts (id) DEFERRABLE INITIALLY DEFERRED,
    user_id uuid NOT NULL REFERENCES users (id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT post_likes_post_id_user_id_key UNIQUE (post_id, user_id)
);
INSERT INTO post_likes_new (post_id, user_id, created_at)
SELECT post_id, user_id, created_at
FROM post_likes;
DROP TABLE post_likes;
ALTER TABLE post_likes_new RENAME TO post_likes;

CREATE TABLE post_tags_new (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    post_id uuid NOT NULL REFERENCES posts (id) DEFERRABLE INITIALLY DEFERRED,
    tag_id uuid NOT NULL REFERENCES tags (id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT post_tags_post_id_tag_id_key UNIQUE (post_id, tag_id)
);
INSERT INTO post_tags_new (post_id, tag_id, created_at)
SELECT post_id, tag_id, created_at
FROM post_tags;
DROP TABLE post_tags;
ALTER TABLE post_tags_new RENAME TO post_tags;

CREATE TABLE post_wiki_documents_new (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    post_id uuid NOT NULL REFERENCES posts (id) DEFERRABLE INITIALLY DEFERRED,
    wiki_document_id uuid NOT NULL REFERENCES wiki_documents (id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT post_wiki_documents_post_id_wiki_document_id_key UNIQUE (post_id, wiki_document_id)
);
INSERT INTO post_wiki_documents_new (post_id, wiki_document_id, created_at)
SELECT post_id, wiki_document_id, created_at
FROM post_wiki_documents;
DROP TABLE post_wiki_documents;
ALTER TABLE post_wiki_documents_new RENAME TO post_wiki_documents;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_oauthaccount"),
        ("core", "0004_postwikidocument_post_wiki_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body_markdown_cache",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="post",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="summary_cache",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="post",
            name="title_cache",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.RunPython(
            backfill_soft_delete_and_post_cache_fields,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=apps.core.models.PostgresEnumField(
                choices=[("published", "Published"), ("draft", "Draft")],
                default="published",
                enum_type="post_status",
                max_length=20,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE comments DROP COLUMN status;",
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="comment",
                    name="status",
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=THROUGH_TABLES_FORWARD_SQL,
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="commentlike",
                    name="pk",
                ),
                migrations.RemoveField(
                    model_name="postlike",
                    name="pk",
                ),
                migrations.RemoveField(
                    model_name="posttag",
                    name="pk",
                ),
                migrations.RemoveField(
                    model_name="postwikidocument",
                    name="pk",
                ),
                migrations.AddField(
                    model_name="commentlike",
                    name="id",
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
                migrations.AddField(
                    model_name="postlike",
                    name="id",
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
                migrations.AddField(
                    model_name="posttag",
                    name="id",
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
                migrations.AddField(
                    model_name="postwikidocument",
                    name="id",
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
                migrations.AddConstraint(
                    model_name="commentlike",
                    constraint=models.UniqueConstraint(
                        fields=("comment", "user"),
                        name="comment_likes_comment_id_user_id_key",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="postlike",
                    constraint=models.UniqueConstraint(
                        fields=("post", "user"),
                        name="post_likes_post_id_user_id_key",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="posttag",
                    constraint=models.UniqueConstraint(
                        fields=("post", "tag"),
                        name="post_tags_post_id_tag_id_key",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="postwikidocument",
                    constraint=models.UniqueConstraint(
                        fields=("post", "wiki_document"),
                        name="post_wiki_documents_post_id_wiki_document_id_key",
                    ),
                ),
            ],
        ),
    ]
