# Generated by Django 5.2.13 on 2026-05-13 01:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_oauthaccount"),
        ("core", "0005_soft_delete_cache_fields_and_surrogate_keys"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostBookmark",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "db_table": "post_bookmarks",
            },
        ),
        migrations.CreateModel(
            name="WikiBookmark",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "db_table": "wiki_bookmarks",
            },
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "deleted_at", "created_at"],
                name="comments_post_del_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="commentlike",
            index=models.Index(
                fields=["user", "-created_at"], name="comment_likes_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postlike",
            index=models.Index(
                fields=["user", "-created_at"], name="post_likes_user_created_idx"
            ),
        ),
        migrations.AddField(
            model_name="postbookmark",
            name="post",
            field=models.ForeignKey(
                db_column="post_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_bookmarks",
                to="core.post",
            ),
        ),
        migrations.AddField(
            model_name="postbookmark",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_bookmarks",
                to="accounts.hiveuser",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="bookmarks",
            field=models.ManyToManyField(
                related_name="bookmarked_posts",
                through="core.PostBookmark",
                to="accounts.hiveuser",
            ),
        ),
        migrations.AddField(
            model_name="wikibookmark",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wiki_bookmarks",
                to="accounts.hiveuser",
            ),
        ),
        migrations.AddField(
            model_name="wikibookmark",
            name="wiki_document",
            field=models.ForeignKey(
                db_column="wiki_document_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wiki_bookmarks",
                to="core.wikidocument",
            ),
        ),
        migrations.AddField(
            model_name="wikidocument",
            name="bookmarks",
            field=models.ManyToManyField(
                related_name="bookmarked_wiki_documents",
                through="core.WikiBookmark",
                to="accounts.hiveuser",
            ),
        ),
        migrations.AddIndex(
            model_name="postbookmark",
            index=models.Index(
                fields=["user", "-created_at"], name="post_bm_user_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="postbookmark",
            constraint=models.UniqueConstraint(
                fields=("post", "user"), name="post_bookmarks_post_id_user_id_key"
            ),
        ),
        migrations.AddIndex(
            model_name="wikibookmark",
            index=models.Index(
                fields=["user", "-created_at"], name="wiki_bm_user_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="wikibookmark",
            constraint=models.UniqueConstraint(
                fields=("wiki_document", "user"),
                name="wiki_bookmarks_document_id_user_id_key",
            ),
        ),
    ]
