# Generated by Django 5.2.13 on 2026-05-26 06:29

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_ingestionjob_source_document_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="WikiDocumentEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("embedding_model", models.CharField(max_length=100)),
                ("embedding_dim", models.IntegerField()),
                ("embedding", apps.core.models.VectorField(dimensions=1536)),
                ("content_hash", models.CharField(max_length=64)),
                ("provider", models.CharField(max_length=50)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "wiki_document",
                    models.ForeignKey(
                        db_column="wiki_document_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="core.wikidocument",
                    ),
                ),
                (
                    "wiki_revision",
                    models.ForeignKey(
                        db_column="wiki_revision_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_embeddings",
                        to="core.wikirevision",
                    ),
                ),
            ],
            options={
                "db_table": "wiki_document_embeddings",
                "indexes": [
                    models.Index(
                        fields=["wiki_revision"], name="wiki_doc_embed_revision_idx"
                    ),
                    models.Index(
                        fields=["embedding_model", "-updated_at"],
                        name="wiki_doc_emb_model_upd_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("wiki_document", "embedding_model"),
                        name="uq_wiki_document_embeddings_document_model",
                    )
                ],
            },
        ),
    ]
