# Generated by Django 5.2.13 on 2026-05-27 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_wikidocumentembedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wikirevisionsource",
            name="source_chunk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wiki_revision_sources",
                to="core.sourcechunk",
            ),
        ),
    ]
