name: Build, Scan, and Push Image

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    uses: Hallym-Workerbees/hivewiki-ci/.github/workflows/build-scan-push-image.yml@main
    with:
      dockerfile: ./Dockerfile
      context: .
      aws_region: ap-northeast-2
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
